### PR TITLE
Bugfix

### LINKED ISSUE #40: Mount tcp!ftrv.se!564
Using the mount tool against tcp!ftrv.se!564 leads to a minetest server crash

```
2020-12-02 00:10:36: ACTION[Server]: bebebeko uses core:connect, pointing at [nothing]
Attached to tcp!ftrv.se!564
2020-12-02 00:10:51: ACTION[Main]: Server: Shutting down
2020-12-02 00:10:54: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'core' in callback environment_Step(): ...in/../share/minetest/builtin/common/misc_helpers.lua:480: table index is nil
2020-12-02 00:10:54: ERROR[Main]: stack traceback:
2020-12-02 00:10:54: ERROR[Main]:       ...in/../share/minetest/builtin/common/misc_helpers.lua:480: in function 'copy'
2020-12-02 00:10:54: ERROR[Main]:       [string "/root/.minetest/mods/core/platform.lua"]:276: in function 'next_pos'
2020-12-02 00:10:54: ERROR[Main]:       [string "/root/.minetest/mods/core/platform.lua"]:332: in function 'spawn_child'
2020-12-02 00:10:54: ERROR[Main]:       [string "/root/.minetest/mods/core/platform.lua"]:312: in function 'func'
2020-12-02 00:10:54: ERROR[Main]:       /usr/bin/../share/minetest/builtin/common/after.lua:20: in function '?'
2020-12-02 00:10:54: ERROR[Main]:       /usr/bin/../share/minetest/builtin/game/register.lua:433: in function </usr/bin/../share/minetest/builtin/game/register.lua:417>
2020-12-02 00:10:54: ERROR[Main]: stack traceback:```

### LINKED ISSUE #42: "Polling user management . . ." in infinite loop
```
2020-12-02 02:52:59: WARNING[Main]: system-wide share not found at "/minetest_compiled/share/minetest"
2020-12-02 02:52:59: WARNING[Main]: system-wide share found at "/usr/bin/../share/minetest"
2020-12-02 02:52:59: [Main]: Automatically selecting world at [/root/.minetest/worlds/world]
2020-12-02 02:52:59: WARNING[Main]: \!/ Mod security should never be disabled, as it allows any mod to access the host machine.Mods should use minetest.request_insecure_environment() instead \!/
2020-12-02 02:52:59: WARNING[Main]: Undeclared global variable "kind" accessed at /usr/local/share/lua/5.1/graph.lua:497
2020-12-02 02:52:59: WARNING[Main]: Undeclared global variable "nocreate" accessed at /usr/local/share/lua/5.1/graph.lua:294
Attached to tcp!inferno!2002
cmdchan is available

2020-12-02 02:52:59: WARNING[Main]: /!\ You are using old player file backend. This backend is deprecated and will be removed in a future release /!\
2020-12-02 02:52:59: WARNING[Main]: Switching to SQLite3 or PostgreSQL is advised, please read http://wiki.minetest.net/Database_backends.
2020-12-02 02:52:59: WARNING[Main]: /!\ You are using old auth file backend. This backend is deprecated and will be removed in a future release /!\
2020-12-02 02:52:59: WARNING[Main]: Switching to SQLite3 is advised, please read http://wiki.minetest.net/Database_backends.
        .__               __                   __
  _____ |__| ____   _____/  |_  ____   _______/  |_
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|
      \/        \/     \/          \/     \/
2020-12-02 02:52:59: ACTION[Main]: World at [/root/.minetest/worlds/world]
2020-12-02 02:52:59: ACTION[Main]: Server for gameid="devtest" listening on 0.0.0.0:30000.
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
2020-12-02 02:53:41: ACTION[Server]: bebebeka [10.115.130.1] joins game. List of players: bebebeka
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
2020-12-02 02:53:54: ACTION[Server]: bebebeka leaves game. List of players:
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
Polling user management . . .
```

### PR DESCRIPTION
**Pull request by dievri**
User management service polled after registry is mounted

Connections and graph stored per player

Resolves #40, Resolves #42

### CODE REVIEW

File: mods/core/automount.lua [hunk 1]
```diff
@@ -10,15 +11,33 @@ poll_user_management = function(root_cmdchan)
     end
 end
 
+mount_registry = function(root_cmdchan)
+    local response = root_cmdchan:execute("mount -A tcp!registry.dev.metacoma.io!30100 /mnt/registry"):gsub("%s+", "")
```
Comment (metacoma) [inline mods/core/automount.lua]: maybe parametrize the registry address?

**Review by metacoma — CHANGES_REQUESTED** [review]

**Review by metacoma — APPROVED** [review]
